apiVersion: v1
kind: Secret
metadata:
  name: {{ include "superset.fullname" . }}-secret
  labels:
    {{- include "superset.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
type: Opaque
stringData:
  SUPERSET_SECRET_KEY: {{ required "secretKey is required" .Values.secretKey | quote }}
  SUPERSET_GUEST_TOKEN_JWT_SECRET: {{ default .Values.secretKey .Values.embedding.guestTokenJwtSecret | quote }}
  SUPERSET_GUEST_TOKEN_JWT_EXP_SECONDS: {{ .Values.embedding.guestTokenExpSeconds | quote }}
  SUPERSET_ADMIN_USERNAME: {{ .Values.admin.username | quote }}
  SUPERSET_ADMIN_PASSWORD: {{ required "admin.password is required" .Values.admin.password | quote }}
  SUPERSET_SQLALCHEMY_DATABASE_URI: {{ include "superset.postgres.uri" . | quote }}
  SUPERSET_ALLOWED_ORIGINS: {{ .Values.embedding.allowedOrigins | quote }}
  POSTGRES_PASSWORD: {{ required "postgres.password is required" .Values.postgres.password | quote }}
