{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "superset.fullname" . }}-route
  labels:
    {{- include "superset.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host | quote }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "superset.fullname" . }}-svc
    weight: 100
  port:
    targetPort: http
  tls:
    termination: {{ .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
  wildcardPolicy: None
{{- end }}
