apiVersion: v1
kind: Service
metadata:
  name: {{ include "superset.fullname" . }}-svc
  labels:
    {{- include "superset.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "superset.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
